name: diff
version: 0.1.2
authors:
- Adam Singer <financeCoding@gmail.com>
description: A diff library
homepage: https://github.com/dart-gde/diff.dart
environment:
  sdk: '>=1.0.0 <3.0.0'
dev_dependencies:
  test: '^1.3.0'